name: Release

on:
  push:
    branches: insights-multiarch

jobs: 
  release:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with: 
          submodules: true
      - name: Setup Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v3
        with:
          version: latest
      - name: Build collectd in docker
        run: |
          set -x
          RELEASE_VERSION="${GITHUB_REF##*/}"
          RELEASE_VERSION="${RELEASE_VERSION:1}"
          debugoutput="insights-collectd-debug-${RELEASE_VERSION}.tar.gz"
          outputgz="insights-collectd-${RELEASE_VERSION}.tar.gz"
          outputzip="insights-collectd-${RELEASE_VERSION}.zip"

          image=collectd-bundle
          docker buildx build --platform linux/amd64,linux/arm64 --build-arg insight_version=${RELEASE_VERSION} -t $image .

          cid=$(docker create --platform linux/arm64 $image true)

          docker export $cid | tar --delete 'dev' 'proc' 'etc' 'sys' 'collectd-symbols' | gzip -f - > $outputgz
          docker export $cid | tar --delete 'dev' 'proc' 'etc' 'sys' 'collectd' | gzip -f - > $debugoutput
          tar -tzf $outputgz
          # tar xzf $outputgz && zip $outputzip $(tar ztf $outputgz)

          # assets=()
          # for asset in $outputzip $outputgz $debugoutput; do
          #   assets+=("-a" "$asset")
          # done
      
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
